name: Windows Server 2025 VM with Tailscale and RDP

on:
  workflow_dispatch:

env:
  VM_NAME: WinServer2025-Tailscale-RDP
  VM_RAM: 64GB
  VM_DISK: C:\HyperV\VirtualHardDisks\WinServer2025-Tailscale-RDP.vhdx
  VM_DISK_SIZE_BYTES: 1099511627776  # 1 TB in bytes
  VM_CPU_COUNT: 8
  TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

jobs:
  setup-vm:
    runs-on: windows-2025

    steps:
      - name: Create folder for VHD if missing
        shell: powershell
        run: |
          if (-not (Test-Path (Split-Path $env:VM_DISK))) {
            New-Item -ItemType Directory -Force -Path (Split-Path $env:VM_DISK)
          }

      - name: Create VHD
        shell: powershell
        run: |
          New-VHD -Path $env:VM_DISK -SizeBytes $env:VM_DISK_SIZE_BYTES -Dynamic

      - name: Create VM
        shell: powershell
        run: |
          New-VM -Name $env:VM_NAME -MemoryStartupBytes $env:VM_RAM -Generation 2 -NewVHDPath $env:VM_DISK
          Set-VMProcessor -VMName $env:VM_NAME -Count $env:VM_CPU_COUNT

      - name: Start VM
        shell: powershell
        run: |
          Start-VM -Name $env:VM_NAME
          Write-Host "VM started, waiting for OS setup (15 min)"
          Start-Sleep -Seconds 900

      - name: Configure Tailscale and RDP on VM
        shell: powershell
        id: setup_vm
        run: |
          $rdpUser = "rdpuser"
          $rdpPass = [System.Web.Security.Membership]::GeneratePassword(16,3)

          Invoke-Command -VMName $env:VM_NAME -ScriptBlock {
            param($user, $pass, $authKey)

            New-LocalUser -Name $user -Password (ConvertTo-SecureString $pass -AsPlainText -Force) -FullName "RDP User" -Description "User pentru RDP"
            Add-LocalGroupMember -Group "Administrators" -Member $user

            # Enable RDP
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

            # Install Tailscale
            Invoke-WebRequest -Uri "https://tailscale.com/install.ps1" -UseBasicParsing | Invoke-Expression
            tailscale up --authkey=$authKey --accept-routes

            Start-Sleep -Seconds 20

            $ip = tailscale ip -4
            Write-Output "Tailscale IP: $ip"

            [PSCustomObject]@{IP=$ip;User=$user;Password=$pass} | ConvertTo-Json
          } -ArgumentList $rdpUser, $rdpPass, $env:TAILSCALE_AUTHKEY -OutVariable result

          $resultJson = $result[-1]
          Write-Host "RDP și Tailscale Info: $resultJson"
          $obj = $resultJson | ConvertFrom-Json
          Write-Output "::set-output name=TAILSCALE_IP::$($obj.IP)"
          Write-Output "::set-output name=RDP_USER::$($obj.User)"
          Write-Output "::set-output name=RDP_PASS::$($obj.Password)"

      - name: Run VM for 6 hours
        shell: powershell
        run: |
          Write-Host "Running VM for 6 hours"
          Start-Sleep -Seconds 21600

      - name: Stop VM
        shell: powershell
        run: |
          Stop-VM -Name $env:VM_NAME -Force
          Write-Host "VM stopped."

      - name: Output connection info
        run: |
          echo "Tailscale IP: ${{ steps.setup_vm.outputs.TAILSCALE_IP }}"
          echo "RDP Username: ${{ steps.setup_vm.outputs.RDP_USER }}"
          echo "RDP Password: ${{ steps.setup_vm.outputs.RDP_PASS }}"
          
